In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.cluster import KMeans

from yellowbrick.cluster import KElbowVisualizer, SilhouetteVisualizer, InterclusterDistance

from sklearn import metrics
from numpy import corrcoef
from scipy.stats import pearsonr

### Similarity between new user 5 and the other users

We ignore the data instance if the rating for that particular movie is missing

In [75]:
user1 = [1, 5, 4, 3]

In [76]:
user2 = [2, 4, 3, 4, 2]

In [77]:
user3 = [2, 3, 4, 3, 5]

In [78]:
user4 = [2, 3, 2, 5, 3]

In [79]:
user5 = [5, 5, 1, 4]

In [80]:
user6 = [4, 5, 2, 4, 5]

Pearson correlation between user 1 and user 5:

In [10]:
user1_1and5 = [1, 3]

In [11]:
user5_1and5 = [5, 1]

In [12]:
pearsonr(user1_1and5, user5_1and5)

(-1.0, 1.0)

In [14]:
corrcoef(user1_1and5, user5_1and5)

array([[ 1., -1.],
       [-1.,  1.]])

Pearson correlation between user 2 and user 5:

In [16]:
user2_2and5 = [2, 3, 4, 2]

In [17]:
user5_2and5 = [5, 5, 1, 4]

In [18]:
pearsonr(user2_2and5, user5_2and5)

(-0.7816608327818949, 0.2183391672181051)

In [19]:
corrcoef(user2_2and5, user5_2and5)

array([[ 1.        , -0.78166083],
       [-0.78166083,  1.        ]])

Pearson correlation between user 3 and user 5:

In [20]:
user3_3and5 = [2, 4, 5]

In [21]:
user5_3and5 = [5, 5, 1]

In [22]:
pearsonr(user3_3and5, user5_3and5)

(-0.7559289460184544, 0.4543710516570102)

In [23]:
corrcoef(user3_3and5, user5_3and5)

array([[ 1.        , -0.75592895],
       [-0.75592895,  1.        ]])

Pearson correlation between user 4 and user 5:

In [70]:
user4_4and5 = [2, 2, 3]

In [71]:
user5_4and5 = [5, 5, 4]

In [72]:
pearsonr(user4_4and5, user5_4and5)

(-0.9999999999999999, 9.486373847239934e-09)

In [73]:
corrcoef(user4_4and5, user5_4and5)

array([[ 1., -1.],
       [-1.,  1.]])

### Similarity between new user 6 and the other users

Pearson correlation between user 1 and user 6:

In [28]:
user1_1and6 = [1, 5, 4, 3]

In [29]:
user6_1and6 = [4, 5, 4, 5]

In [30]:
pearsonr(user1_1and6, user6_1and6)

(0.50709255283711, 0.49290744716289003)

In [31]:
corrcoef(user1_1and6, user6_1and6)

array([[1.        , 0.50709255],
       [0.50709255, 1.        ]])

Pearson correlation between user 2 and user 6:

In [37]:
user2_2and6 = [2, 4, 3, 4]

In [38]:
user6_2and6 = [4, 5, 2, 5]

In [39]:
pearsonr(user2_2and6, user6_2and6)

(0.492365963917331, 0.507634036082669)

In [40]:
corrcoef(user2_2and6, user6_2and6)

array([[1.        , 0.49236596],
       [0.49236596, 1.        ]])

Pearson correlation between user 3 and user 6:

In [126]:
user3_3and6 = [2, 3, 4, 3, 5]

In [127]:
user6_3and6 = [4, 5, 2, 4, 5]

In [128]:
pearsonr(user3_3and6, user6_3and6)

(0.0, 1.0000000000000002)

In [129]:
corrcoef(user3_3and6, user6_3and6)

array([[1., 0.],
       [0., 1.]])

Pearson correlation between user 4 and user 6:

In [45]:
user4_4and6 = [2, 3, 2, 5]

In [46]:
user6_4and6 = [4, 5, 2, 4]

In [47]:
pearsonr(user4_4and6, user6_4and6)

(0.3746343246326776, 0.6253656753673225)

In [49]:
corrcoef(user4_4and6, user6_4and6)

array([[1.        , 0.37463432],
       [0.37463432, 1.        ]])

### Let us find the prediction scores for not yet watch movies for user 5

In [62]:
#Function for finding the mean
def find_mean(userA):
    sum = 0;
    for x in userA:
        sum += x
    mean = sum/len(userA)
    return mean

In [113]:
#Function for calculating the prediction score
def score_prediction(userPredict, users, movieP, sims):
    i = 0;
    numerator = 0.00;
    denominator = 0.00;
    for user in users:
        print("sims[i]: "+ str(sims[i]))
        numerator += sims[i]*(user[movieP]-find_mean(user))
        print("numerator: "+ str(numerator))
        denominator += sims[i]
        print("denominator: "+ str(denominator))
        i = i+1
    score = find_mean(userPredict)+(numerator/denominator)
    return score

In [114]:
users = [user1, user2, user3, user4]
simsWith5 = [-1.0, -0.78, -0.75, -0.99]

In [115]:
movie2_prediction = score_prediction(user5, users, 1, simsWith5)

sims[i]: -1.0
numerator: -1.75
denominator: -1.0
sims[i]: -0.78
numerator: -2.5300000000000002
denominator: -1.78
sims[i]: -0.75
numerator: -2.2300000000000004
denominator: -2.5300000000000002
sims[i]: -0.99
numerator: -2.2300000000000004
denominator: -3.5200000000000005


In [116]:
movie2_prediction

4.3835227272727275

The score prediction for user5 to movie 2 is: 4

In [119]:
movie2_prediction = score_prediction(user5, users, 3, simsWith5)

sims[i]: -1.0
numerator: 0.25
denominator: -1.0
sims[i]: -0.78
numerator: -0.53
denominator: -1.78
sims[i]: -0.75
numerator: -0.2300000000000001
denominator: -2.5300000000000002
sims[i]: -0.99
numerator: -2.21
denominator: -3.5200000000000005


In [120]:
movie2_prediction

4.377840909090909

The score prediction for user5 to movie 4 is: 4

### Let us find the prediction scores for not yet watch movies for user 6

In [123]:
users = [user2, user4]
simsWith6 = [0.49, 0.37]

In [124]:
movie2_prediction = score_prediction(user6, users, 4, simsWith6)

sims[i]: 0.49
numerator: -0.49
denominator: 0.49
sims[i]: 0.37
numerator: -0.49
denominator: 0.86


In [125]:
movie2_prediction

3.4302325581395348

The score prediction for user6 to movie 5 is: 3